### ISSUE TITLE
[QUESTION] aws_serverlessapplicationrepository_cloudformation_stack

### ISSUE THREAD

**Issue by sthysel** [awslabs/aws-athena-query-federation#418]
I have a question that I don't think is related to a bug or feature request. 

This really is a quation about terraform's aws_serverlessapplicationrepository_cloudformation_stack support for this application.

I'm using terraform to provision this application as follows:

```
# there seems to be no way to add the catalog specific connection strings
# "Catalog specific Connection Strings can be added later"
resource "aws_serverlessapplicationrepository_cloudformation_stack" "rds_connector" {
  name           = "${var.dev_prefix}rds-connector"
  application_id = "arn:aws:serverlessrepo:us-east-1:292517598671:applications/AthenaJdbcConnector"
  capabilities = [
    "CAPABILITY_IAM",
    #"CAPABILITY_RESOURCE_POLICY",
  ]
  parameters = {
    DefaultConnectionString : var.du_rds_connection_default
    LambdaFunctionName : "${var.dev_prefix}du_rds"
    SecretNamePrefix : "PVAthenaJdbcFederation"
    SecurityGroupIds : join(",", data.aws_security_groups.default_security_group.ids)
    SubnetIds : join(",", data.aws_subnet_ids.default_subnet.ids)
    SpillBucket : aws_s3_bucket.spill_bucket.bucket
  }
}
```
There seems to be no way in terraform to add environment variables to an existing lambda. I'm using the multi-catalogue functionality so I need to add connection strings for my various source catalogues.

How do I add these connection parameters to the env variables of the lambda created by the AthenaJdbcConnector application either during its construction or after the fact ?

**Comment by avirtuos** [comment]
Unfortunately, we don't presently have much experience using terraform in this way.  Have you posed this question to them? Adding environment variables to an existing Lambda function can be done from the Lambda console rather easily but I'm assuming you are looking for a way to do this via terraform only (not a manually post-processing step)?

**Comment by sthysel** [comment]
I believe the aws_serverlessapplicationrepository_cloudformation_stack just enables whatever is exposed in the template. So if there are no mechanism to populate the template it can't be done using that resource type.

I'm referring to https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-jdbc/athena-jdbc.yaml, where I need to add 

db1_connection_
db2_connection_

to Variables so those connections can be used as Multiplexing handler parameters

```
Resources:
  JdbcConnectorConfig:
    Type: 'AWS::Serverless::Function'
    Properties:
      Environment:
        Variables:
          disable_spill_encryption: !Ref DisableSpillEncryption
          spill_bucket: !Ref SpillBucket
          spill_prefix: !Ref SpillPrefix
          default: !Ref DefaultConnectionString
```

Is there a way to populate those ?
