### ISSUE TITLE
[BUG] Output 'ApplicationOutputName' not found in stack  with connector dynamodb-connector

### ISSUE THREAD

**Issue by seanWLawrence** [awslabs/aws-athena-query-federation#516]
**Describe the bug**
Output 'ApplicationOutputName' not found in stack 

**To Reproduce**
1. Deploy stack and use `GetAttr` for  'Outputs.ApplicationOutputName' (also tried 'ApplicationOutputName'). 

I used the CDK to deploy this and get the attribute to use in a lambda function. Here's an example:

```typescript
 this.athenaDynamoDbConnector = new sam.CfnApplication(
      this,
      'athena-dynamodb-connector',
      {
        location: {
          /**
           * Found on https://serverlessrepo.aws.amazon.com/applications/us-east-1/292517598671/AthenaDynamoDBConnector
           */
          applicationId:
            'arn:aws:serverlessrepo:us-east-1:292517598671:applications/AthenaDynamoDBConnector',

          /**
           * Found on https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-dynamodb/athena-dynamodb.yaml
           */
          semanticVersion: '2021.37.1',
        },
        parameters: {
          AthenaCatalogName: 'dynamodb',
          SpillBucket: props.athenaResultsBucket.bucketName,
          SpillPrefix: 'dynamodb-connector-spill',
          LambdaTimeout: '900',
          LambdaMemory: '3008',
          DisableSpillEncryption: 'false',
        },
      },
    );
```

And then using it elsewhere:

```ts
const environment = {
        AthenaDynamoDBConnectorApplicationName: props.athenaDynamoDbConnector
          .getAtt('Outputs.ApplicationOutputName')
          .toString()
}
```

**Expected behavior**
The application name attribute value. I'm sorry if my mental model is wrong on this, I just expected this to follow the return values from the [AWS::Serverless::Application construct](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-application.html#sam-resource-application-return-values)

**Screenshots / Exceptions / Errors**
`Output 'ApplicationOutputName' not found in stack` shown. I looked at the template and don't see this value as an output. 

**Connector Details (please complete the following information):**
 - Version: 2021.37.1
 - Name dynamodb

**Additional context**
I'm happy to contribute this output if it's not too much work!

**Comment by janmran** [comment]
Doesn't seem like a bug in the connector code. Can you refer to this link for `getAtt` usage? https://bobbyhadz.com/blog/getatt-aws-cdk It says it should be called on a Cfn resourced or invoke through Fn class.

**Comment by seawildau** [comment]
The issue here is that the `AWS::Serverless::Application` resource creates a nested stack after the serverless transform, so when you use `getAtt(...)` you are only able to retrieve attributes that are exposed explicitly as CloudFormation `Outputs`. The `dynamodb-connector` template doesn't expose any outputs so you can't actually fetch any attributes from the nested stack.

If we added an outputs section to the [dynamodb template](https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-dynamodb/athena-dynamodb.yaml) then you could access those outputs using `getAtt()` from CDK.

There's other use cases for this, such as getting the Lambda function ARN from the nested stack so that you can actually use the connector in an Athena / glue table via CDK.

**Comment by akuzin1** [comment]
Thank you for reaching out. As you had mentioned, we currently do not include the `ApplicationOutputName` as an output because it's a static value, matching the string passed in as the `AthenaCatalogName` parameter which can be directly embedded elsewhere. If there is a specific use case where that does not work and there is a need for output values to be specifically returned from the stack, feel free to reopen the ticket and provide additional detail.

**Comment by seawildau** [comment]
> If there is a specific use case where that does not work and there is a need for output values to be returned from the stack instead, feel free to reopen the ticket and provide additional detail.

Not all desired outputs are static values like `ApplicationOutputName`, my example of the lambda function ARN of the serverless application above being one of them. Not having the lambda function ARN as an available output means that you have to write a custom resource to retrieve the ARN if you want to reference the connector in Athena. CloudFormation example below, but this applies equally to CDK applications trying to instantiate athena federated connectors via CloudFormation from the published serverless application repo:

```
Resources:
  MyDynamoDBConnector:
    Type: AWS::Serverless::Application
      Properties:
        Location:
          ApplicationId: 'arn:aws:serverlessrepo:us-east-1:292517598671:applications/AthenaDynamoDBConnector'
          SemanticVersion: '2021.37.1'
      Parameters:
        ...
      

  MyAthenaDataCatalog:
    Type: AWS::Athena::DataCatalog
    Properties:
      Name: MyCustomDataCatalog
      Type: Lambda
      Description: Custom Catalog Description
      Parameters:
        function: !GetAtt MyDynamoDBConnector.Outputs.LambdaFunctionArn # doesn't work, this output doesn't exist
```
